// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzXpnpkPsmC-N5TJ1-wwQLnFQUJQb4ScE',
    appId: '1:1070651645721:web:ef35e10ade04f247ce6f88',
    messagingSenderId: '1070651645721',
    projectId: 'tumbyahmadjamil',
    authDomain: 'tumbyahmadjamil.firebaseapp.com',
    storageBucket: 'tumbyahmadjamil.firebasestorage.app',
    measurementId: 'G-DMRG9PKT7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtxYIfFWw1m4ErJ9ZZf5qAF6o46ygFCZA',
    appId: '1:1070651645721:android:44bbd60570ac763dce6f88',
    messagingSenderId: '1070651645721',
    projectId: 'tumbyahmadjamil',
    storageBucket: 'tumbyahmadjamil.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZfzAxgr1PpmAoK5QE_95Z9C1XWu3Pcsg',
    appId: '1:1070651645721:ios:974dc7eb128b06f6ce6f88',
    messagingSenderId: '1070651645721',
    projectId: 'tumbyahmadjamil',
    storageBucket: 'tumbyahmadjamil.firebasestorage.app',
    iosBundleId: 'com.ahmadjamil.tum',
  );
}
